### ISSUE TITLE
Data challenge:  Data Dispatcher:  interface to POMS feasibility

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#127]
Identify what if any changes would need to be made to POMS to have it communicate to Metacat / Rucio /Data dispatcher rather than to SAM.

**Comment by calcuttj** [comment]
POMS is a front end to [fife_launch](https://cdcvs.fnal.gov/redmine/projects/fife_utils/wiki/Fife_launch_Reference) -- fife_launch is itself a front end to jobsub_submit

fife_launch submits a job which executes a wrapper. Normally, this is fife_wrap, but this can be changed. 

fife_launch accepts a parameter (ifdh_art) n its config file which enables the use of sam. See [here](https://cdcvs.fnal.gov/redmine/projects/fife_utils/repository/revisions/master/entry/libexec/fife_wrap#L918). This adds the following flags to the command that is run within the main job:
<pre>cmdlist.append("--sam-web-uri=%s" % self.cpurl)
cmdlist.append("--sam-process-id=%s" % self.consumerid)</pre>

That is just some background, if we want this to work with other data handlers, there is some amount of editing to the wrapper that we need to do

**Comment by calcuttj** [comment]
To-do: try running some simple lar module (eventdump.fcl or maybe one that just counts events in files -- I think there's one that does this) on a metacat dataset (make a testing dataset with some dune files as below).

<pre>(metacat_env) metacat$ metacat query files from dune:all limit 10
default:genieNtp_20130423_lbne_lbneCD1_anuflux_nuebarflux_nuebar_g280_Ar40_5000_1.root
default:prodcosmics_lbne35t_onewindow_36_20150220T201755_gen.root
default:prodgenie_nu_dune10kt_45deg_1x2x6_724_20160428T225204_gen_19b77090-f145-4b37-a413-4d6d266f6b37.root
default:prodgenie_nu_dune10kt_r90deg_1x2x6_693_20160429T003737_gen_bfe9c6e6-bc7f-4198-baff-35b4533115aa.root
default:prodgenie_nu_dune10kt_45deg_1x2x6_721_20160428T225210_gen_2fef3ce9-667f-4ed2-b78d-fa66fd846dc8.root
default:prodgenie_nu_dune10kt_3mmpitch_1x2x6_175_20160428T214942_gen_59facfdd-77ab-4384-bac5-09fb687d93ef.root
default:prodgenie_nu_dune10kt_45deg_1x2x6_722_20160428T225152_gen_d92967a1-21d0-4cac-b7b3-55c928c4e0fd.root
default:prodgenie_nu_dune10kt_45deg_1x2x6_728_20160428T225420_gen_2f36a238-5fc6-4e3b-a385-2fa661c527c6.root
default:prodgenie_nu_dune10kt_3mmpitch_1x2x6_278_20160428T215057_gen_395585ff-2fcc-44e4-8030-12e7160d062d.root
default:prodgenie_nu_dune10kt_3mmpitch_1x2x6_924_20160428T222314_gen_699b32ee-b7f2-4a43-aa8d-3696c6b4596f.root
</pre>

might have to use docker/singularity (probably the latter since I think docker is discouraged on the worker nodes)  this so that metacat can be ran easily in the job (need to have some non-standard python modules + installed metacat -- turn it into a container, send it with the jobs to list files). 

[FIfe_wrap also creates a sam project](https://cdcvs.fnal.gov/redmine/projects/fife_utils/repository/revisions/master/entry/libexec/fife_wrap#L1912) to handle the data transfer -- replace with data dispatcher functionality

**Comment by calcuttj** [comment]
Igor gave a talk at the CM with a description and set of instructions for [Metacat](https://indico.fnal.gov/event/50217/contributions/241884/attachments/155316/202207/MetaCat%20for%20DUNE%20Collaboration%20May%202022.pdf)

Has he given anything similar for Data Dispatcher? There's [this](https://indico.fnal.gov/event/50217/contributions/241590/attachments/155338/202241/Data%20Dispatcher%20Overview%20and%20Status.pdf) but no instructions

**Comment by ivmfnal** [comment]
See https://data-dispatcher.readthedocs.io/en/latest/index.html

**Comment by calcuttj** [comment]
Receiving this error
<pre>(metacat_env) data_dispatcher$ dd login x509 calcuttj /tmp/x509up_u52312 
dd: unrecognized operand ‘login’
Try 'dd --help' for more information.
</pre>

**Comment by ivmfnal** [comment]
I think you picked the OS "dd" instead of Data Dispatcher UI dd.
Have you followed the Data Dispatcher [UI installation instructions](https://data-dispatcher.readthedocs.io/en/latest/install.html) ?
What is your PATH ?

**Comment by calcuttj** [comment]
Hey Igor, sorry this took a while for me to get back to. I took vacation last week. Indeed that was the issue. Trying it out now and getting this error

<pre>(metacat_env) data_dispatcher$ dd login x509 calcuttj /tmp/x509up_u52312 
Traceback (most recent call last):
  File "/nashome/c/calcuttj/.local/bin/dd", line 33, in <module>
    sys.exit(load_entry_point('data_dispatcher==1.12.0', 'console_scripts', 'dd')())
  File "/nashome/c/calcuttj/.local/bin/dd", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/cvmfs/larsoft.opensciencegrid.org/products/python/v3_9_2/Linux64bit+3.10-2.17/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/cvmfs/larsoft.opensciencegrid.org/products/python/v3_9_2/Linux64bit+3.10-2.17/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: data_dispatcher

</pre>

**Comment by calcuttj** [comment]
Fixed this myself by pointing pythonpath to the data dispatcher top dir

**Comment by calcuttj** [comment]
Realized I had to call 

<pre>dd login x509 username cert_file.pem key_file.pem </pre>

before 
<pre>dd login x509 username proxy_file</pre>

but I'm unsure where to find the cert and key files

**Comment by ivmfnal** [comment]
I get mine from https://www.cilogon.org/home

**Comment by ivmfnal** [comment]
you can also try 
```
dd login x509 username proxy_file proxy_file
```
because proxy file in fact contains both cert and key

**Comment by StevenCTimm** [comment]
this is actually a duplicate.. now replaced in post-project by issue #255
