### ISSUE TITLE
Ops:  deletes not working at Lancaster due to not supported delete protocol

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#176]

**Comment by StevenCTimm** [comment]
022-07-29 17:34:46,362  root    10  CRITICAL    reaper[0/1] Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/daemons/reaper/reaper.py", line 589, in reaper
    prot = rsemgr.create_protocol(rse_info, 'delete', scheme=scheme, logger=logger)
  File "/usr/local/lib/python3.6/site-packages/rucio/rse/rsemanager.py", line 195, in create_protocol
    protocol_attr = select_protocol(rse_settings, operation, scheme, domain)
  File "/usr/local/lib/python3.6/site-packages/rucio/rse/rsemanager.py", line 166, in select_protocol
    candidates = _get_possible_protocols(rse_settings, operation, scheme, domain)
  File "/usr/local/lib/python3.6/site-packages/rucio/rse/rsemanager.py", line 142, in _get_possible_protocols
    ' found : %s.' % str(rse_settings))
rucio.common.exception.RSEProtocolNotSupported: RSE does not support requested protocol.
Details: No protocol for provided settings found : {'availability_delete': True, 'availability_read': True, 'availability_write': True, 'credentials': None, 'deterministic': True, 'domain': ['lan', 'wan'], 'id': '8cfa37080fab4a9ebeb8c15e70ccf00e', 'lfn2pfn_algorithm': 'hash', 'protocols': [{'hostname': 'fal-pygrid-30.lancs.ac.uk', 'scheme': 'https', 'port': 0, 'prefix': '/dpm/lancs.ac.uk/home/dune', 'impl': 'rucio.rse.protocols.gfalv2.Default', 'domains': {'lan': {'read': 0, 'write': 0, 'delete': 0}, 'wan': {'read': 1, 'write': 1, 'delete': 1, 'third_party_copy': 1}}, 'extended_attributes': None}, {'hostname': 'fal-pygrid-30.lancs.ac.uk', 'scheme': 'root', 'port': 0, 'prefix': '/dpm/lancs.ac.uk/home/dune', 'impl': 'rucio.rse.protocols.gfalv2.Default', 'domains': {'lan': {'read': 0, 'write': 0, 'delete': 0}, 'wan': {'read': 2, 'write': 2, 'delete': 2, 'third_party_copy': 1}}, 'extended_attributes': None}], 'qos_class': None, 'rse': 'LANCASTER', 'rse_type': 'DISK', 'sign_url': None, 'staging_area': False, 'verify_checksum': True, 'volatile': False, 'read_protocol': 1, 'write_protocol': 1, 'delete_protocol': 1, 'third_party_copy_protocol': 1}.

**Comment by StevenCTimm** [comment]
This was found to be due to the fact that Brandon had hard-wired the reaper to run only with gsiftp protocol.  he has removed this restriction now and reaping has happened at LANCASTEr.
