### ISSUE TITLE
non-metacat copies fail silently

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#268]
IF a file does not have metacat info and we are trying to copy it to a non-deterministic RSE it fails, but it fails
quietly, the conveyor-submitter just throwing an exception and no output to the user.  Brandon suggests adding a
explicit Not_In_Metacat exception, I agree.

**Comment by StevenCTimm** [comment]
Here is the exception from the conveyor-submitter that happens in this case

5221
2024-01-29 18:25:54,364 root 1 DEBUG conveyor-submitter[bb37350:0/1]: Starting to submit transfers for User Subscriptions (https://fts3-public.cern.ch:8446)
5222
2024-01-29 18:25:54,438 root 1 DEBUG conveyor-submitter[bb37350:0/1]: Heartbeat renewed
5223
2024-01-29 18:25:54,439 root 1 DEBUG conveyor-submitter[bb37350:0/1]: submitjob: transfers=['DUNE_US_BNL_SDCC,DUNE_CERN_EOS--b01eb50d71d6424fbc67e547e849e484->FNAL_DCACHE'], job_params={'account': dunepro, 'verify_checksum': 'both', 'copy_pin_lifetime': None, 'bring_online': None, 'job_metadata': {'issuer': 'rucio', 'multi_sources': True}, 'overwrite': False, 'priority': 3, 'max_time_in_queue': 5}
5224
2024-01-29 18:25:54,459 urllib3.connectionpool 1 DEBUG Starting new HTTPS connection (1): metacat.fnal.gov:9443
5225
2024-01-29 18:25:54,602 urllib3.connectionpool 1 DEBUG https://metacat.fnal.gov:9443 "GET /dune_meta_prod/app/data/file?with_metadata=yes&with_provenance=yes&with_datasets=no&name=121068.1-justin-prod-sched01.dune.hep.ac.uk.logs.tgz&namespace=justin-logs HTTP/1.1" 404 14
5226
2024-01-29 18:25:54,607 root 1 ERROR conveyor-submitter[bb37350:0/1]: Failed to prepare requests ['b01eb50d71d6424fbc67e547e849e484(justin-logs:121068.1-justin-prod-sched01.dune.hep.ac.uk.logs.tgz)'] state to SUBMITTING. Mark it SUBMISSION_FAILED and abort submission.
5227
Traceback (most recent call last):
5228
File "/usr/local/lib/python3.6/site-packages/rucio/daemons/conveyor/common.py", line 432, in submit_transfer
5229
transfer_core.mark_submitting(transfer, external_host=transfertool_obj.external_host, logger=logger)
5230
File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 388, in new_funct
5231
result = function(*args, **kwargs)
5232
File "/usr/local/lib/python3.6/site-packages/rucio/core/transfer.py", line 327, in mark_submitting
5233
transfer.dest_url,
5234
File "/usr/local/lib/python3.6/site-packages/rucio/core/transfer.py", line 139, in dest_url
5235
self._dest_url = self._generate_dest_url(self.dst, self.rws, self.protocol_factory, self.operation_dest)
5236
File "/usr/local/lib/python3.6/site-packages/rucio/core/transfer.py", line 237, in _generate_dest_url
5237
dest_path = construct_surl(dsn, rws.scope.external, rws.name, naming_convention)
5238
File "/usr/local/lib/python3.6/site-packages/rucio/common/utils.py", line 615, in construct_surl
5239
return _SURL_ALGORITHMS[naming_convention](dsn, scope, filename)
5240
File "/opt/rucio/permissions/fermilab/dune/path_gen.py", line 56, in construct_surl_dune_metacat
5241
metadata = jsondata["metadata"]
5242
TypeError: 'NoneType' object is not subscriptable

**Comment by StevenCTimm** [comment]
This is still ongoing in rucio v33

**Comment by StevenCTimm** [comment]
They fail now but at least there is an exception..
