### ISSUE TITLE
SUBMISSION_FAILED status on a number of rules

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#477]
We are seeing a number of inbound rules to FNAL_DCACHE fail with SUBMISSION_FAILED

There's an associated exception in the conveyor_submitter log

Traceback (most recent call last):
11972
  File "/usr/local/lib/python3.9/site-packages/rucio/daemons/conveyor/common.py", line 393, in submit_transfer
11973
    transfer_core.mark_submitting(transfer, external_host=transfertool_obj.external_host, logger=logger)
11974
  File "/usr/local/lib/python3.9/site-packages/rucio/db/sqla/session.py", line 454, in new_funct
11975
    result = function(*args, session=session, **kwargs)
11976
  File "/usr/local/lib/python3.9/site-packages/rucio/core/transfer.py", line 346, in mark_submitting
11977
    transfer.dest_url,
11978
  File "/usr/local/lib/python3.9/site-packages/rucio/core/transfer.py", line 145, in dest_url
11979
    self._dest_url = self._generate_dest_url(self.dst, self.rws, self.protocol_factory, self.operation_dest)
11980
  File "/usr/local/lib/python3.9/site-packages/rucio/core/transfer.py", line 252, in _generate_dest_url
11981
    dest_path = construct_surl(dsn, rws.scope.external, rws.name, naming_convention)
11982
  File "/usr/local/lib/python3.9/site-packages/rucio/common/utils.py", line 621, in construct_surl
11983
    return _SURL_ALGORITHMS[naming_convention](dsn, scope, filename)
11984
  File "/opt/rucio/permissions/fermilab/dune/path_gen.py", line 42, in construct_surl_dune_metacat
11985
    metacat_url = config.config_get('policy', 'metacat_base_url') or os.environ.get("METACAT_SERVER_URL")
11986
  File "/usr/local/lib/python3.9/site-packages/rucio/common/config.py", line 210, in config_get
11987
    raise err
11988
  File "/usr/local/lib/python3.9/site-packages/rucio/common/config.py", line 191, in config_get
11989
    return convert_type_fnc(get_config().get(section, option))
11990
  File "/usr/lib64/python3.9/configparser.py", line 792, in get
11991
    raise NoOptionError(option, section)
11992
configparser.NoOptionError: No option 'metacat_base_url' in section: 'policy'

**Comment by StevenCTimm** [comment]
This was traced to a missing metacat URL in the conveyor-submitter config file.  Fixed.
